import file1 from "./../../../assets/files/ADVERT-SUPPLY-AND-DELIVERY-AS-WELL-AS-INSTALLATION-OF-EQUIPMENT-FOR-THE-ECOWAS-EARLY-WARNING-SYSTEM-IN-NIGER-BENIN-AND-GHANA.pdf";
import file2 from "./../../../assets/files/PUBLIC-ANNOUNCEMENT1.pdf";
import file3 from "./../../../assets/files/ADVERTISEMENT-OF-VACANCY-HEAD-OF-FINANCE-AND-ADMINISTRATION-DIVISION-P5.-AFRICAN-COURT-OF-HUMAN-AND-PEOPLESRIGHTS-1.pdf";
import file4 from "./../../../assets/files/ADVERTISEMENT-OF-VACANCY-INTERPRETER-TRANSLATOR-PORTUGUESE-P4-AFRICAN-COURT-ON-HUMAN-AND-PEOPLESRIGHTS.pdf";

export const announcements = [
    {
        title: 'SUPPLY AND DELIVERY AS WELL AS, INSTALLATION OF EQUIPMENT FOR THE ECOWAS EARLY WARNING SYSTEM IN NIGER, BENIN AND GHANA',
        file: file1
    },
    {
        title: 'PUBLIC ANNOUNCEMENT',
        file: file2
    },
    {
        title: 'ADVERTISEMENT OF VACANCY – HEAD OF FINANCE AND ADMINISTRATION DIVISION- P5. AFRICAN COURT OF HUMAN AND PEOPLES RIGHTS',
        file: file3
    },
    {
        title: 'ADVERTISEMENT OF VACANCY-INTERPRETER-TRANSLATOR-PORTUGUESE P4 AFRICAN COURT ON HUMAN AND PEOPLES RIGHTS',
        file: file4
    },
]