const MFA_THEME_VARIANT = 'MFA_THEME_VARIANT';
const MFA_VIEW_MODE = 'MFA_VIEW_MODE';
const MFA_BASE_SERVER_URL = 'MFA_BASE_SERVER_URL';

export const MFA_CONSTANTS = {MFA_THEME_VARIANT, MFA_BASE_SERVER_URL, MFA_VIEW_MODE};
